apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sickrage-pod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sickrage-pod
    spec:
      containers:
      - image: linuxserver/sickrage
        name: sickrage-pod
        ports:
        - containerPort: 8081
          hostPort: 8081
        volumeMounts:
          - name: sickrage-pv-config
            mountPath: /config
      volumes:
      - name: sickrage-pv-config
        hostPath:
          path: /data/k8s/configs/sickrage 
      restartPolicy: Always
